# Generated by Django 4.2.1 on 2024-11-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quiz_faculty_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='faculty_name',
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_template',
            field=models.ImageField(default='C:\\Users\\KRINA KAKADIYA\\OneDrive\\Pictures\\Screenshots\\quiz_xl_image.png', upload_to=''),
        ),
    ]
