# Generated by Django 4.2.1 on 2024-11-11 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_remove_quiz_faculty_name_quiz_quiz_template'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='quiz_template',
            new_name='quiz_template_display',
        ),
    ]
