# Generated by Django 4.2.1 on 2024-11-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_remove_quiz_quiz_template_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='display_image',
            field=models.ImageField(blank=True, default='images/user.png', editable=False, null=True, upload_to=''),
        ),
    ]
