# Generated by Django 4.2.1 on 2024-11-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_quiz_display_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='display_image',
            field=models.ImageField(default='images/user.png', upload_to=''),
        ),
    ]
