# Generated by Django 4.2.1 on 2024-11-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_alter_quiz_display_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='display_image',
        ),
    ]
